apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
data:
  application.yaml: |
    spring:
      r2dbc:
        password: password
        username: user
        url: r2dbc:postgresql://db-postgresql:5432/mydatabase
