apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ok-metrics-monitor
  namespace: monitoring
  labels:
    release: stack
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: ok-metrics
  endpoints:
  - port: metrics
    interval: 15s
    path: /actuator/prometheus
    honorLabels: true


