{
 "title": "Ok dashboards",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max persentil",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress mediana",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.5 percentil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.95 percentil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress 0.99 percentil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress 0.95 percentil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.99 percentil",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"ok-app-ingress\", status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}