spring:
  flyway:
    enabled: true
  application:
    name: Microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8000
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

